# Generated by Django 3.2.13 on 2022-05-17 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='club_logo',
            new_name='club_logo_url',
        ),
    ]
