# Generated by Django 3.2.13 on 2022-05-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_api', '0002_rename_club_logo_club_club_logo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='category',
            field=models.ManyToManyField(to='club_api.Category'),
        ),
    ]
