# Generated by Django 3.2.13 on 2022-05-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_api', '0004_alter_club_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='introduce_long',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
