# Generated by Django 3.2.13 on 2022-05-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_api', '0005_club_introduce_long'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club_Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to='club_logo')),
            ],
        ),
    ]
