# Generated by Django 3.2.13 on 2022-05-25 08:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club_api', '0006_club_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='interested',
            field=models.ManyToManyField(related_name='interested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='club',
            name='member',
            field=models.ManyToManyField(related_name='member', to=settings.AUTH_USER_MODEL),
        ),
    ]
