# Generated by Django 3.2.13 on 2022-05-26 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_api', '0007_auto_20220525_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interesting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('clubs', models.ManyToManyField(to='club_api.Club')),
            ],
        ),
    ]
