# Generated by Django 3.2.13 on 2022-05-26 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club_api', '0009_qna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qna',
            name='answer',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='qna',
            name='answerer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answerer', to=settings.AUTH_USER_MODEL),
        ),
    ]
