# Generated by Django 3.2.13 on 2022-05-27 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club_api', '0010_auto_20220526_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='interested',
        ),
        migrations.AddField(
            model_name='club',
            name='like',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club',
            name='qna',
            field=models.ManyToManyField(blank=True, related_name='qna', to='club_api.QnA'),
        ),
        migrations.AddField(
            model_name='qna',
            name='club_name',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='club',
            name='member',
            field=models.ManyToManyField(blank=True, related_name='member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='club',
            name='president_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='club',
            name='president_phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='qna',
            name='answer',
            field=models.TextField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qna',
            name='answerer',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='answerer', to='login_api.user'),
            preserve_default=False,
        ),
    ]
