# Generated by Django 3.2.13 on 2022-05-27 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club_api', '0012_auto_20220527_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='club',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='club_api.answer'),
        ),
    ]
