# Generated by Django 3.2.13 on 2022-05-27 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club_api', '0014_rename_club_question_club_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer',
            new_name='answer_text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='question_text',
        ),
        migrations.RemoveField(
            model_name='club',
            name='qna',
        ),
        migrations.AddField(
            model_name='club',
            name='question',
            field=models.ManyToManyField(blank=True, related_name='question', to='club_api.Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='club_api.answer'),
        ),
        migrations.DeleteModel(
            name='QnA',
        ),
    ]
