# Generated by Django 3.2.13 on 2022-05-27 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_api', '0015_auto_20220527_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_text',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='answerer',
        ),
    ]
