# Generated by Django 3.2.13 on 2022-05-27 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club_api', '0019_alter_answer_answerer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='club_api.answer'),
        ),
    ]
