# Generated by Django 3.2.13 on 2022-05-27 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club_api', '0020_alter_question_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.AddField(
            model_name='club',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='questions', to='club_api.Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='club_api.answer'),
        ),
    ]
