# Generated by Django 3.2.13 on 2022-05-27 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club_api', '0022_answer_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.ForeignKey(default='18', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='club_api.answer'),
        ),
    ]
