# Generated by Django 3.2.13 on 2022-05-28 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club_api', '0023_auto_20220527_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='president',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='president', to=settings.AUTH_USER_MODEL),
        ),
    ]
