# Generated by Django 3.2.13 on 2022-05-28 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club_api', '0024_club_president'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_logo_url',
            field=models.URLField(default='https://w.namu.la/s/90b3132a0a6406eaf98a49e5d7bf9ef7f7c689036f892663e4c22de357550b7789a027e7dfb76ccf853857f6ec8fba152d756ba50388c886d35fb69e0740d22e8509ffa55a7374af9aa4b32083dd149c53c290ca6b057f8074efcc9895adf6a2'),
        ),
        migrations.AlterField(
            model_name='club',
            name='president',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='president', to=settings.AUTH_USER_MODEL),
        ),
    ]
