# Generated by Django 3.2.13 on 2022-06-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_api', '0030_auto_20220531_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
