# Generated by Django 3.2.13 on 2022-06-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_api', '0031_alter_club_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='recruit',
            field=models.CharField(default='2022/06/01', max_length=20),
            preserve_default=False,
        ),
    ]
