# Generated by Django 3.2.13 on 2022-06-02 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_api', '0032_club_recruit'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='apply_link',
            field=models.URLField(blank=True),
        ),
    ]
