# Generated by Django 3.2.13 on 2022-05-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interesting_Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='interesting',
            field=models.ManyToManyField(to='login_api.Interesting_Club'),
        ),
    ]
